### ISSUE TITLE
first version, a skeleton

### ISSUE THREAD

**Issue by yegor256** [polystat/polystat#1]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#3](https://github.com/polystat/polystat/issues/3) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#3](https://github.com/polystat/polystat/issues/3), [#4](https://github.com/polystat/polystat/issues/4) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 4 puzzles [#3](https://github.com/polystat/polystat/issues/3), [#4](https://github.com/polystat/polystat/issues/4), [#5](https://github.com/polystat/polystat/issues/5), [#6](https://github.com/polystat/polystat/issues/6) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 5 puzzles [#3](https://github.com/polystat/polystat/issues/3), [#4](https://github.com/polystat/polystat/issues/4), [#5](https://github.com/polystat/polystat/issues/5), [#6](https://github.com/polystat/polystat/issues/6), [#7](https://github.com/polystat/polystat/issues/7) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#4](https://github.com/polystat/polystat/issues/4), [#5](https://github.com/polystat/polystat/issues/5), [#6](https://github.com/polystat/polystat/issues/6) are still not solved; solved: [#3](https://github.com/polystat/polystat/issues/3), [#7](https://github.com/polystat/polystat/issues/7).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#5](https://github.com/polystat/polystat/issues/5), [#6](https://github.com/polystat/polystat/issues/6) are still not solved; solved: [#3](https://github.com/polystat/polystat/issues/3), [#4](https://github.com/polystat/polystat/issues/4), [#7](https://github.com/polystat/polystat/issues/7).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#5](https://github.com/polystat/polystat/issues/5) is still not solved; solved: [#3](https://github.com/polystat/polystat/issues/3), [#4](https://github.com/polystat/polystat/issues/4), [#6](https://github.com/polystat/polystat/issues/6), [#7](https://github.com/polystat/polystat/issues/7).
