### ISSUE TITLE
Temp directory need to be manually deleted to apply changes in source files

### ISSUE THREAD

**Issue by APotyomkin** [polystat/polystat#23]
It is not intuitive to delete temp files each time when you change source code. It is can be confusing if I forgot to delete it and see no changes take effect.

**Comment by yegor256** [comment]
@APotyomkin what is the scenario you are talking about? I'm a bit lost.

**Comment by APotyomkin** [comment]
@yegor256 I'm talking about testing Polystat by changing the content of the source code in the `foo.eo` file.
For example, I have such file foo.eo:
```
[x] > foo
  div. > @
    5
    x

```
I ran the analysis:
```
java -jar polystat-1.0-SNAPSHOT-jar-with-dependencies.jar sandbox temp
```
And got the results:
```
Error: \perp at {x=0, ?-4-3=\any}
```
I changed the source code:
```
[] > foo
  div. > @
    42
    12

```
I reran the analysis:
```
java -jar polystat-1.0-SNAPSHOT-jar-with-dependencies.jar sandbox temp
```
And I got the same result:
```
Error: \perp at {x=0, ?-4-3=\any}
```
But i expected to see:
```
No errors
```

As I understood, it's because `temp` folder already has `foo.xml` file, so it will not be regenerated.
So I need to change or clear the `temp` directory to rerun the analysis each time, or somehow wrap it to do it automatically.

**Comment by yegor256** [comment]
@andreoss can you please fix this? I believe we should just make [this check](https://github.com/polystat/polystat/blob/master/src/main/java/org/polystat/Program.java#L77) stronger: it should verify the date of the file, not only its existence.

**Comment by yegor256** [comment]
@APotyomkin should be solved now, please try

**Comment by APotyomkin** [comment]
@yegor256 yeap, all right, thanks
