### ISSUE TITLE
XMIR.java:44-47: The current implementation is very...

### ISSUE THREAD

**Issue by 0pdd** [polystat/polystat#4]
The puzzle `1-408fd3a6` from #1 has to be resolved: 

https://github.com/polystat/polystat/blob/e10511ef689769d34b5e2ce38958db5cd87e1e98/src/main/java/org/polystat/XMIR.java#L44-L47

The puzzle was created by @yegor256 on 02-Jul-21. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@mximp yes, we moved it to eo repo

**Comment by mximp** [comment]
@yegor256 actually, I just realised it was renamed to `Program`.
The puzzle still exists.

**Comment by mximp** [comment]
@yegor256 can you please elaborate on this puzzle.
I just run the test for a program:
```
+package org.polystat

[a b] > test
  add. > @
    div. a b
    div.
      div. b a
      div.
        five
        a

  [] > five
    5 > @
```

Fetching `final XML test = program.apply("\\Phi.test.five");` gives the following result which seems correct:
```
<o line="12" name="five" pos="2">
  <o base="org.eolang.int" data="int" line="13" name="@" pos="4">5</o>
</o>
```

**Comment by yegor256** [comment]
@mximp try to put `test` and `five` in different files

**Comment by mximp** [comment]
@yegor256 The following input:
```
+package org.polystat

[] > five
  5 > @
```
```
+package org.polystat

+alias org.polystat.five

[a b] > test
  add. > @
    div. a b
    div.
      div. b a
      div.
        fv
        a

  five > fv
```

gives correct output for `program.apply("\\Phi.test.fv")`:
```
<o base="org.polystat.five" line="14" name="fv" pos="2"/>
```

**Comment by yegor256** [comment]
@mximp maybe it's time to close this ticket than

**Comment by 0pdd** [comment]
The puzzle `1-408fd3a6` has disappeared from the source code, that's why I closed this issue.
