### ISSUE TITLE
Delete temporary files automatically

### ISSUE THREAD

**Issue by kniazkov** [polystat/polystat#41]
During operation, Polystat creates temporary files for which we need to specify a folder. To use the application in the "translator" - "Polystat" - "IDE" chain, such files are not needed and they must be deleted. Please add an option that will save such files to a temporary folder (so that you do not have to specify its name) and delete it when the application ends.

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.0`

**Comment by yegor256** [comment]
@kniazkov try version 0.6.0 with a new `--tmp` command line option
