### ISSUE TITLE
Configuration: exclude / include rules

### ISSUE THREAD

**Issue by nikololiahim** [polystat/polystat#56]
## Configs
I suggest implementing this functionality using a configuration file, as well as a corresponding `--config` option for commandline interface. The configuration schema (YAML, TOML, JSON, etc.) is ultimately a matter of preference. To include / exclude rules, I suggest having the following two options in the config file (I will use JSON as an example):
- `excludeRules` is a list of ruleIDs that specifies the rules that WILL NOT be executed during the analysis. All the rules that are not in this list WILL be executed.
- `includeRules` is a list of ruleIDs that specifies the rules that WILL be executed during the analysis. All the rules that are not in this list WILL NOT be exected.

This description requires that the `excludeRules` list and `includeRules` be _mutually-exclusive_, i.e. when one of the lists is present, the other must either be empty or absent. 
An example JSON configuration that would only allow rules 1 - 3 run would look like this:
```json
{
    "includeRules": [
        "rule1", "rule2", "rule3"
    ],
    "excludeRules": [] // may be absent
}
```

## Rule IDs
For now, the rule IDs are only [generated in the SARIF output](https://github.com/polystat/polystat/blob/defb5bf38e41a467872e9e64eca35e41f2e167d6/src/main/java/org/polystat/AsSarif.java#L135-L146). However, they are too verbose to type in a config file and can be made shorter. Examples of how ruleIDs look right now in the SARIF output can be found [here](https://github.com/polystat/polystat/pull/53). (the `results` and `invocations` sections).

@yegor256 @fizruk what do you think?

**Comment by yegor256** [comment]
@nikololiahim I like this idea, let me implement its skeleton quickly

**Comment by yegor256** [comment]
@nikololiahim @fizruk what do you think if we organize this file similar to how it's done here, for example: https://github.com/cqfn/pdd/blob/master/.pdd A configuration file is a collection of command line options, one per line. When Polystat starts, it will read this file from `./.polystat` or from `~/.polystat` or from the path specified by `--config` option. It will simply add all options found in the file to the list of command line args, and then process them together with all others.

**Comment by nikololiahim** [comment]
@yegor256 I like it. Although, I think it isn't necessary to use the commandline arguments _verbatim_, but rather just the corresponding config options. For example, not `--sarif` but `sarif = true` or something similar.

~~I also think that it would be easier to discover and read configs only when the `--config` option is specified. It is unclear what happens when config-file and cmdline args contain conflicting options.~~ 

On the other hand, cmdline args can _override_ config-file options.

**Comment by yegor256** [comment]
@nikololiahim the original idea was to keep this `.polystat` file _literally_ similar to command line options. That's why all options start with `--` in it: https://github.com/cqfn/pdd/blob/master/.pdd This way nobody will have any doubts about how to use this file.

**Comment by nikololiahim** [comment]
@yegor256 Ok, now I understand. So, the include/exclude rules become just `--include r1 r2 r3` or `--exclude r1`. I like it!

**Comment by yegor256** [comment]
@nikololiahim or maybe like this (content of `.polystat`):

```
--sarif
--include r1
--include r2 r3
--exclude r5
```

**Comment by yegor256** [comment]
@nikololiahim maybe you can implement this and suggest a pull request?

**Comment by nikololiahim** [comment]
@yegor256 Ok, I can try.
