### ISSUE TITLE
Polystat.java:70-76: For some reason, the Logger.info()...

### ISSUE THREAD

**Issue by 0pdd** [polystat/polystat#6]
The puzzle `1-6f8eb0a3` from #1 has to be resolved: 

https://github.com/polystat/polystat/blob/2bf114a5a9c2d5a64d47dc8f996c62a338307707/src/main/java/org/polystat/Polystat.java#L70-L76

The puzzle was created by @yegor256 on 02-Jul-21. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
@pollyvolk please assist with this.

**Comment by pollyvolk** [comment]
@mximp Is this issue still in demand? It seems that previous PRs solved the problem or refactored the code. I cannot find "print" instructions

**Comment by pollyvolk** [comment]
I checked Logger.info and Logger.warn output in Git Bash and Windows CMD. Results are in the attachments. Looks like it works. (However my concoles don't recognize the kappa symbol from the result)

**Comment by pollyvolk** [comment]
Also I suggest rename the message "No errors found" to something like "No errors found by analyzers", because after thrown exceptions the current message looks a bit confusing.

**Comment by mximp** [comment]
> Also I suggest rename the message "No errors found" to something like "No errors found by analyzers", because after thrown exceptions the current message looks a bit confusing.

@pollyvolk Agree. Please amend.

**Comment by pollyvolk** [comment]
@mximp Ok. What about the puzzle?

**Comment by mximp** [comment]
@pollyvolk if it's no longer valid just remove it from the code.

**Comment by 0pdd** [comment]
The puzzle `1-6f8eb0a3` has disappeared from the source code, that's why I closed this issue.
